name: Nightly Hello World Workflow

on: 
  schedule:
    - cron: "0 5 * * *" # Runs at 11:00 PM Chicago time (adjusted to UTC)

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Echo Hello World
        run: echo "Hello, World"

